GisRazorPage/GisRazorPage/Pages/A5.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using Newtonsoft.Json;

namespace GisRazorPage.Pages
{
    public class A5Model : PageModel
    {
        public int Year { get; set; } = 2017;
        public string jsonString { get; set; }
        
        public void OnGet()
        {
            Console.WriteLine("Using Data Table");
            A5();
        }

        public void OnPost()
        {
            String tmp = Request.Form["Year"];

            
                try {

                Year = Int32.Parse(tmp);
                A5();
                }
                catch {
                 
                A5();
            }
            
            

            
        }

        

        public void A5()
        {
            string CS = "Data Source=KINKANOM;Initial Catalog=SpatialDB3;Integrated Security=True";
            SqlConnection con = new SqlConnection(CS);
            string command = "DECLARE @input_year INT Select @input_year = year From AirPollutionPM25 WHERE year = "+Year+" Select latitude, longitude From AirPollutionPM25 WHERE year = @input_year";

            SqlDataAdapter da = new SqlDataAdapter(command, con);
            DataTable dt = new DataTable();
            da.Fill(dt);
            string[] columnNames = (from dc in dt.Columns.Cast<DataColumn>()
                                    select dc.ColumnName).ToArray();
            Console.WriteLine(dt.DataSet);

            Console.WriteLine("Test2");

            jsonString = JsonConvert.SerializeObject(dt);
            Console.WriteLine(jsonString);


        }


    }
}

GisRazorPage/GisRazorPage/Pages/AddData.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Data;

using ClosedXML.Excel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using NPOI.HSSF.UserModel;
using System.Data.SqlClient;

namespace GisRazorPage.Pages
{
    public class AddDataModel : PageModel
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        public string fileName = "";
        public string filePath = Directory.GetCurrentDirectory()+@"\Files\";
        public string filePathOutput = @"C:\\Users\\bossa\\Documents\\KMITL\\spatial\\Book2.xlsx";


        public AddDataModel(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        
        public IFormFile Uploadfiles { get; set; }

        public void OnGet()
        {
            
        }
       

        public async Task OnPostAsync()
        {
            //upload File to server
            var Fileupload = Path.Combine(_webHostEnvironment.ContentRootPath, "Files", Uploadfiles.FileName);
            using (var Fs = new FileStream(Fileupload, FileMode.Create))
            {
                await Uploadfiles.CopyToAsync(Fs);
                fileName = Uploadfiles.FileName;
                filePath = filePath + fileName;
                Console.WriteLine(filePath);



                ViewData["Message"] = "The Select File " + Uploadfiles.FileName + " Is Upload Sucessfully ";
                fileName = Uploadfiles.FileName;


            }

            ReadFile();
        }




        public void ReadFile()
        {
            try
            {
                //Creat for Read
                IWorkbook workbook = null;
                FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read);
                if (filePath.IndexOf(".xlsx") > 0)
                    workbook = new XSSFWorkbook(fs);
                else if (filePath.IndexOf(".xls") > 0)
                    workbook = new HSSFWorkbook(fs);

                ISheet sheet = workbook.GetSheetAt(0);


                if (sheet != null)
                {
                    int rowCount = sheet.LastRowNum;
                    Console.WriteLine(rowCount);


                    for (int i = 1; i <= rowCount; i++)
                    {
                        IRow curRow = sheet.GetRow(i);

                        string cellValue0 = curRow.GetCell(0).ToString();
                        string cellValue1 = curRow.GetCell(1).ToString().Replace("'", "''");
                        string cellValue2 = curRow.GetCell(2).ToString();
                        string cellValue3 = curRow.GetCell(3).ToString();
                        string cellValue4 = curRow.GetCell(4).ToString();
                        string cellValue5 = curRow.GetCell(5).ToString();
                        string cellValue6 = curRow.GetCell(6).ToString();
                        string cellValue7 = curRow.GetCell(7).ToString();
                        string cellValue8 = curRow.GetCell(8).ToString();
                        string cellValue9 = curRow.GetCell(9).ToString();
                        string cellValue10 = curRow.GetCell(10).ToString();


                        //Console.WriteLine(cellValue0 + "  " + cellValue1 + "  " + cellValue2 + " " + cellValue3 + " " + cellValue4 + " " + cellValue5 + " " + cellValue6 + " " + cellValue7 + " " + cellValue8 + " " + cellValue9 + " " + cellValue10);


                        string command = "INSERT INTO AirPollutionPM25 ([country],[city],[Year],[pm25],[latitude],[longitude],[population],[wbinc16_text],[Regian],[conc_pm25],[color_pm25],[Geom]) VALUES('" + cellValue0 + "', '" + cellValue1 + "', " + cellValue2 + ", " + cellValue3 + ", " + cellValue4 + ", " + cellValue5 + ", " + cellValue6 + ", '" + cellValue7 + "', '" + cellValue8 + "', '" + cellValue9 + "', '" + cellValue10 + "', geometry::Point(" + cellValue5 + ", " + cellValue4 + ", 4326));";
                        Insert(command);
                        //Console.WriteLine(i);
                    }



                }

            }
            catch (Exception exception)
            {

            }
        }

        public void Insert(string command)
        {
            string CS = "Data Source=KINKANOM;Initial Catalog=SpatialDB3;Integrated Security=True";
            SqlConnection con = new SqlConnection(CS);


            con.Open();
            SqlCommand cmd = new SqlCommand(command, con);
            cmd.ExecuteNonQuery();
            con.Close();


        }

    }
}

GisRazorPage/GisRazorPage/Pages/B5.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using Newtonsoft.Json;

namespace GisRazorPage.Pages
{
    public class B5Model : PageModel
    {
        public string jsonString { get; set; }


        public void OnGet()
        {
            Console.WriteLine("Using Data Table B5");
            B5();
        }



        public void B5()
        {
            string CS = "Data Source=KINKANOM;Initial Catalog=SpatialDB3;Integrated Security=True";
            SqlConnection con = new SqlConnection(CS);
            string command = "DECLARE @bangkok GEOMETRY Select @bangkok = geom From AirPollutionPM25 Where country = 'Thailand' AND city = 'Bangkok' Select TOP 50 country, city, Geom.MakeValid().STDistance(@bangkok) AS distance, latitude, longitude From AirPollutionPM25 Where country != 'Thailand' AND city != 'Bangkok' ORDER BY distance ASC";

            SqlDataAdapter da = new SqlDataAdapter(command, con);
            DataTable dt = new DataTable();
            da.Fill(dt);
            string[] columnNames = (from dc in dt.Columns.Cast<DataColumn>()
                                    select dc.ColumnName).ToArray();
            Console.WriteLine(dt.DataSet);

            Console.WriteLine("B5");

            jsonString = JsonConvert.SerializeObject(dt);
            Console.WriteLine(jsonString);


        }


    }
}

GisRazorPage/GisRazorPage/Pages/ExportExcel.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System.Data;
using System.Data.SqlClient;

namespace GisRazorPage.Pages
{
    public class ExportExcelModel : PageModel
    {
        public string filePathA4 = Directory.GetCurrentDirectory() + @"\Files\A4.xlsx";
        public string filePathB4 = Directory.GetCurrentDirectory() + @"\Files\B4.xlsx";
        public string filePathC4 = Directory.GetCurrentDirectory() + @"\Files\C4.xlsx";
        public string filePathD4 = Directory.GetCurrentDirectory() + @"\Files\D4.xlsx";
        public string country = "";
        public string color = "";
        public int Year = 0;

        public void OnGet()
        {
        }
        

        public ActionResult OnPostDownloadFileA4()
        {
            A4();
            var file = filePathA4;
            return File(new FileStream(file, FileMode.Open), "application/octet-stream", "A4.xlsx");
        }
        public ActionResult OnPostDownloadFileB4()
        {
            B4();
            var file = filePathB4;
            return File(new FileStream(file, FileMode.Open), "application/octet-stream", "B4.xlsx");
        }

        public ActionResult OnPostDownloadFileC4()
        {
            String tmp = Request.Form["country"];
            try
            {
                country = tmp;
                C4();
                var file = filePathC4;
                return File(new FileStream(file, FileMode.Open), "application/octet-stream", "C4.xlsx");
            }
            catch
            {
                return null;
            }
            return null;
        }

        public ActionResult OnPostDownloadFileD4()
        {
            String tmp1 = Request.Form["color"];
            String tmp2 = Request.Form["Year"];
            try
            {
                color = tmp1;
                Year = Int32.Parse(tmp2);
                D4();
                var file = filePathD4;
                return File(new FileStream(file, FileMode.Open), "application/octet-stream", "D4.xlsx");
            }
            catch
            {
                return null;
            }
            return null;
        }

        public void A4()
        {
            string CS = "Data Source=KINKANOM;Initial Catalog=SpatialDB3;Integrated Security=True";
            SqlConnection con = new SqlConnection(CS);
            string command = "Select country, city, pm25, year From AirPollutionPM25 Where pm25 > 50 AND year = 2015";

            SqlDataAdapter da = new SqlDataAdapter(command, con);
            DataTable dt = new DataTable();
            da.Fill(dt);
            string[] columnNames = (from dc in dt.Columns.Cast<DataColumn>()
                                    select dc.ColumnName).ToArray();
            Console.WriteLine(dt.DataSet);

            Console.WriteLine("Test2");

            IWorkbook workbook = new XSSFWorkbook();
            ISheet worksheet = workbook.CreateSheet("Sheet1");


            int rowNumber = 0;
            IRow row = worksheet.CreateRow(rowNumber);

            using (var fs = new FileStream(filePathA4, FileMode.Create, FileAccess.Write))
            {
                row = worksheet.CreateRow(rowNumber++);

                ICell cell = row.CreateCell(0);
                cell = row.CreateCell(0);
                cell.SetCellValue("country");

                cell = row.CreateCell(1);
                cell.SetCellValue("city");

                cell = row.CreateCell(2);
                cell.SetCellValue("pm25");

                cell = row.CreateCell(3);
                cell.SetCellValue("year");

                foreach (DataRow rowTb in dt.Rows)
                {
                    row = worksheet.CreateRow(rowNumber++);
                    cell = row.CreateCell(0);
                    cell.SetCellValue(rowTb["country"].ToString());

                    cell = row.CreateCell(1);
                    cell.SetCellValue(rowTb["city"].ToString());

                    cell = row.CreateCell(2);
                    cell.SetCellValue(rowTb["pm25"].ToString());

                    cell = row.CreateCell(3);
                    cell.SetCellValue(rowTb["year"].ToString());
                }

                workbook.Write(fs);
            }

        }

        public void B4()
        {
            string CS = "Data Source=KINKANOM;Initial Catalog=SpatialDB3;Integrated Security=True";
            SqlConnection con = new SqlConnection(CS);
            string command = "Select AVG(pm25) AS pm25avg, country From AirPollutionPM25 GROUP BY country ORDER BY pm25avg DESC";

            SqlDataAdapter da = new SqlDataAdapter(command, con);
            DataTable dt = new DataTable();
            da.Fill(dt);
            string[] columnNames = (from dc in dt.Columns.Cast<DataColumn>()
                                    select dc.ColumnName).ToArray();
            Console.WriteLine(dt.DataSet);

            Console.WriteLine("Test2");

            IWorkbook workbook = new XSSFWorkbook();
            ISheet worksheet = workbook.CreateSheet("Sheet1");


            int rowNumber = 0;
            IRow row = worksheet.CreateRow(rowNumber);

            using (var fs = new FileStream(filePathB4, FileMode.Create, FileAccess.Write))
            {
                row = worksheet.CreateRow(rowNumber++);

                ICell cell = row.CreateCell(0);
                cell = row.CreateCell(0);
                cell.SetCellValue("pm25avg");

                cell = row.CreateCell(1);
                cell.SetCellValue("country");

                foreach (DataRow rowTb in dt.Rows)
                {
                    row = worksheet.CreateRow(rowNumber++);
                    cell = row.CreateCell(0);
                    cell.SetCellValue(rowTb["pm25avg"].ToString());

                    cell = row.CreateCell(1);
                    cell.SetCellValue(rowTb["country"].ToString());
                }

                workbook.Write(fs);
            }

        }

        public void C4()
        {
            string CS = "Data Source=KINKANOM;Initial Catalog=SpatialDB3;Integrated Security=True";
            SqlConnection con = new SqlConnection(CS);
            string command = "DECLARE @input_country NVARCHAR(255) Select @input_country = '"+ country+"' From AirPollutionPM25 Select country, pm25, Year From AirPollutionPM25 Where country = @input_country ORDER BY year";

            SqlDataAdapter da = new SqlDataAdapter(command, con);
            DataTable dt = new DataTable();
            da.Fill(dt);
            string[] columnNames = (from dc in dt.Columns.Cast<DataColumn>()
                                    select dc.ColumnName).ToArray();
            Console.WriteLine(dt.DataSet);

            Console.WriteLine("Test2");

            IWorkbook workbook = new XSSFWorkbook();
            ISheet worksheet = workbook.CreateSheet("Sheet1");


            int rowNumber = 0;
            IRow row = worksheet.CreateRow(rowNumber);

            using (var fs = new FileStream(filePathC4, FileMode.Create, FileAccess.Write))
            {
                row = worksheet.CreateRow(rowNumber++);

                ICell cell = row.CreateCell(0);
                cell = row.CreateCell(0);
                cell.SetCellValue("country");

                cell = row.CreateCell(1);
                cell.SetCellValue("pm25");

                cell = row.CreateCell(2);
                cell.SetCellValue("Year");

                foreach (DataRow rowTb in dt.Rows)
                {
                    row = worksheet.CreateRow(rowNumber++);
                    cell = row.CreateCell(0);
                    cell.SetCellValue(rowTb["country"].ToString());

                    cell = row.CreateCell(1);
                    cell.SetCellValue(rowTb["pm25"].ToString());

                    cell = row.CreateCell(2);
                    cell.SetCellValue(rowTb["Year"].ToString());
                }

                workbook.Write(fs);
            }

        }

        public void D4()
        {
            string CS = "Data Source=KINKANOM;Initial Catalog=SpatialDB3;Integrated Security=True";
            SqlConnection con = new SqlConnection(CS);
            string command = "DECLARE @input_year NVARCHAR(255) Select @input_year = '"+Year+"' From AirPollutionPM25 DECLARE @input_color_pm NVARCHAR(255) Select @input_color_pm = '"+color+"' From AirPollutionPM25 Select @input_year AS year, @input_color_pm AS color, SUM(population) AS totalPm25 From AirPollutionPM25";

            SqlDataAdapter da = new SqlDataAdapter(command, con);
            DataTable dt = new DataTable();
            da.Fill(dt);
            string[] columnNames = (from dc in dt.Columns.Cast<DataColumn>()
                                    select dc.ColumnName).ToArray();
            Console.WriteLine(dt.DataSet);

            Console.WriteLine("Test2");

            IWorkbook workbook = new XSSFWorkbook();
            ISheet worksheet = workbook.CreateSheet("Sheet1");


            int rowNumber = 0;
            IRow row = worksheet.CreateRow(rowNumber);

            using (var fs = new FileStream(filePathD4, FileMode.Create, FileAccess.Write))
            {
                row = worksheet.CreateRow(rowNumber++);

                ICell cell = row.CreateCell(0);
                cell = row.CreateCell(0);
                cell.SetCellValue("year");

                cell = row.CreateCell(1);
                cell.SetCellValue("color");

                cell = row.CreateCell(2);
                cell.SetCellValue("totalPm25");

                foreach (DataRow rowTb in dt.Rows)
                {
                    row = worksheet.CreateRow(rowNumber++);
                    cell = row.CreateCell(0);
                    cell.SetCellValue(rowTb["year"].ToString());

                    cell = row.CreateCell(1);

GisRazorPage/GisRazorPage/Pages/A5.cshtml
@page
@model GisRazorPage.Pages.A5Model
@{

}
<h1>ผลลัพท์ข้อ 5A</h1>
<div class="container">
    <main role="main" class="pb-3">
        <form method="POST">
            <div class="mb-3">
                <label class="form-label">Year </label>
                <input class="form-control" name="Year">
            </div>
            <p>This Year = @Model.Year</p>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

            

        </main>
</div>

@section MapSection {
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>ArcGIS Developer Guide: Display a map (2D)</title>
  <style>
    html,
    body,
    #viewDiv {
      padding: 0;
      margin: 0;
      height: 100%;
      width: 100%;
    }
  </style>

  <link rel="stylesheet" href="https://js.arcgis.com/4.19/esri/themes/light/main.css">
  <script src="https://js.arcgis.com/4.19/"></script>

  <script>
    require([
     "esri/config",
      "esri/Map",
      "esri/views/MapView",
    "esri/Graphic",
    "esri/layers/GraphicsLayer"
    ], function (esriConfig,Map, MapView, Graphic, GraphicsLayer) {

      esriConfig.apiKey = "AAPK09a77ed38c3b4ea6b2172804f6280ef4j3opY4UGsKsZXuw4QgT0rfKX0wXAVwwPBuX8qAEQ14ToC4fA9Fg2Qm8tCyrXH_fY";
      const map = new Map({
        basemap: "arcgis-topographic" // Basemap layer
      });

      const view = new MapView({
        map: map,
        center: [-118.805, 34.027],
        zoom: 2, // scale: 72223.819286
        container: "viewDiv",
        constraints: {
          snapToZoom: false
        }
      });

        const graphicsLayer = new GraphicsLayer();
        map.add(graphicsLayer);
 

const dataJson = @Html.Raw(@Model.jsonString);
      console.log(dataJson);

for(let i = 0; i< dataJson.length; i++){
 const point = { //Create a point
    type: "point",
    longitude: dataJson[i].longitude,
    latitude: dataJson[i].latitude
 };
 const simpleMarkerSymbol = {
    type: "simple-marker",
    color: [226, 119, 40],  // Orange
    outline: {
        color: [255, 255, 255], // White
        width: 1
    }
 };

 const pointGraphic = new Graphic({
    geometry: point,
    symbol: simpleMarkerSymbol
 });
 graphicsLayer.add(pointGraphic);
}
//}        



    });
  </script>

</head>

<body>
  <div id="viewDiv"></div>
</body>




</html>

}

GisRazorPage/GisRazorPage/Pages/AddData.cshtml
@page
@model GisRazorPage.Pages.AddDataModel
@{
    
}

<div class="text-center">
    <h1 class="display-4">Upload Excel File To Server</h1>
    <hr />
    <form method="POST" enctype="multipart/form-data">
        <input id="File1" type="file" asp-for="Uploadfiles" />
        <input id="Submit1" type="submit" value="Upload File ..." class="btn-success" />
        <hr />
    </form>
    <p>เมื่ออัพโหลดไฟล์เสร็จ จะแสดงข้อความ</p>
    <b>@ViewData["Message"]</b>

</div>

GisRazorPage/GisRazorPage/Pages/B5.cshtml
@page
@model GisRazorPage.Pages.B5Model
@{

}
<h1>ผลลัพท์ข้อ 5B</h1>

@section MapSection {
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>ArcGIS Developer Guide: Display a map (2D)</title>
  <style>
    html,
    body,
    #viewDiv {
      padding: 0;
      margin: 0;
      height: 100%;
      width: 100%;
    }
  </style>

  <link rel="stylesheet" href="https://js.arcgis.com/4.19/esri/themes/light/main.css">
  <script src="https://js.arcgis.com/4.19/"></script>

  <script>
    require([
     "esri/config",
      "esri/Map",
      "esri/views/MapView",
    "esri/Graphic",
    "esri/layers/GraphicsLayer"
    ], function (esriConfig,Map, MapView, Graphic, GraphicsLayer) {

      esriConfig.apiKey = "AAPK09a77ed38c3b4ea6b2172804f6280ef4j3opY4UGsKsZXuw4QgT0rfKX0wXAVwwPBuX8qAEQ14ToC4fA9Fg2Qm8tCyrXH_fY";
      const map = new Map({
        basemap: "arcgis-topographic" // Basemap layer
      });

      const view = new MapView({
        map: map,
        center: [-118.805, 34.027],
        zoom: 2, // scale: 72223.819286
        container: "viewDiv",
        constraints: {
          snapToZoom: false
        }
      });

        const graphicsLayer = new GraphicsLayer();
        map.add(graphicsLayer);
 

const dataJson = @Html.Raw(@Model.jsonString);
      console.log(dataJson);

for(let i = 0; i< dataJson.length; i++){
 const point = { //Create a point
    type: "point",
    longitude: dataJson[i].longitude,
    latitude: dataJson[i].latitude
 };
 const simpleMarkerSymbol = {
    type: "simple-marker",
    color: [226, 119, 40],  // Orange
    outline: {
        color: [255, 255, 255], // White
        width: 1
    }
 };

 const pointGraphic = new Graphic({
    geometry: point,
    symbol: simpleMarkerSymbol
 });
 graphicsLayer.add(pointGraphic);
}
//}        



    });
  </script>

</head>

<body>
  <div id="viewDiv"></div>
</body>




</html>

}

GisRazorPage/GisRazorPage/Pages/C5.cshtml
@page
@model GisRazorPage.Pages.C5Model
@{
}
<h1>ผลลัพท์ข้อ 5C</h1>


@section MapSection {
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>ArcGIS Developer Guide: Display a map (2D)</title>
  <style>
    html,
    body,
    #viewDiv {
      padding: 0;
      margin: 0;
      height: 100%;
      width: 100%;
    }
  </style>

  <link rel="stylesheet" href="https://js.arcgis.com/4.19/esri/themes/light/main.css">
  <script src="https://js.arcgis.com/4.19/"></script>

  <script>
    require([
     "esri/config",
      "esri/Map",
      "esri/views/MapView",
    "esri/Graphic",
    "esri/layers/GraphicsLayer"
    ], function (esriConfig,Map, MapView, Graphic, GraphicsLayer) {

      esriConfig.apiKey = "AAPK09a77ed38c3b4ea6b2172804f6280ef4j3opY4UGsKsZXuw4QgT0rfKX0wXAVwwPBuX8qAEQ14ToC4fA9Fg2Qm8tCyrXH_fY";
      const map = new Map({
        basemap: "arcgis-topographic" // Basemap layer
      });

      const view = new MapView({
        map: map,
        center: [-118.805, 34.027],
        zoom: 2, // scale: 72223.819286
        container: "viewDiv",
        constraints: {
          snapToZoom: false
        }
      });

        const graphicsLayer = new GraphicsLayer();
        map.add(graphicsLayer);
 

const dataJson = @Html.Raw(@Model.jsonString);
      console.log(dataJson);

for(let i = 0; i< dataJson.length; i++){
 const point = { //Create a point
    type: "point",
    longitude: dataJson[i].longitude,
    latitude: dataJson[i].latitude
 };
 const simpleMarkerSymbol = {
    type: "simple-marker",
    color: [226, 119, 40],  // Orange
    outline: {
        color: [255, 255, 255], // White
        width: 1
    }
 };

 const pointGraphic = new Graphic({
    geometry: point,
    symbol: simpleMarkerSymbol
 });
 graphicsLayer.add(pointGraphic);
}
//}        



    });
  </script>

</head>

<body>
  <div id="viewDiv"></div>
</body>




</html>

}

GisRazorPage/GisRazorPage/Pages/ExportExcel.cshtml
@page
@model GisRazorPage.Pages.ExportExcelModel
@{
    
}
<h1>Download Excel Query</h1>
<div>
    <form method="POST">
        <button type="submit" asp-page-handler="DownloadFileA4">Download ข้อ 4A</button>
        <button type="submit" asp-page-handler="DownloadFileB4">Download ข้อ 4B</button>
        
    </form>
    <br>
    <br>
    <hr />
    <p>โปรดใส่ข้อมูล country</p>
    <form method="POST">
        <div class="mb-3">
                <label class="form-label">country </label>
                <input class="form-control" name="country">
            </div>
        <button type="submit" asp-page-handler="DownloadFileC4">Download ข้อ 4C</button>
    </form>
    <hr />
    <br>
    <br>
    <br>
    <br>
    <hr />
    <p>โปรดใส่ข้อมูล country และ Year</p>
    <form method="POST">
        <div class="mb-3">
                <label class="form-label">color </label>
                <input class="form-control" name="color">
            </div>
            <div class="mb-3">
                <label class="form-label">Year </label>
                <input class="form-control" name="Year">
            </div>
        <button type="submit" asp-page-handler="DownloadFileD4">Download ข้อ 4D</button>
    </form>
    <hr />
    <br>
    <br>
</div>

GisRazorPage/GisRazorPage/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    //Layout = "_Layout";
}

<div class="text-center">
    <h1 class="display-4">Welcome To Wittaya Super GIS Map</h1>
    <h2>รายชื่อทีมงาน WittayaSuperGisMap</h2>
    <h3>62050222 นายวิทยา วรจันทร์เพ็ญศรี</h3>
    <h3>62050243 นายหฤษฎ์ ชวลิตเบญจ</h3>
    <h3>62050250 นายอี้วเต๋อ หลิน</h3>
</div>